services:
  mariadb: # no modificar
    image: docker.io/bitnami/mysql:8.0
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=db_myapp
      - MYSQL_DATABASE=myapp
    ports:
      - '3306:3306'

  # Imagen para usar y descargar laravel
  myapp:
    image: docker.io/bitnami/laravel:10
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=db_myapp
      - DB_DATABASE=myapp
    volumes:
      - './:/app'
    depends_on:
      - mariadb

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '8001:80'
    environment:
      - PMA_ARBITRARY=1

