name: Deploy Laravel Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    # Checkout del código del repositorio
    - name: Checkout code
      uses: actions/checkout@v2

    # Configurar PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, bcmath, sqlite, gd, curl
    # Extensiones necesarias en Laravel

    # Instalar dependencias de Composer
    - name: Install dependencies with Composer
      run: |
        curl -sS https://getcomposer.org/installer | php
        php composer.phar install --no-dev --optimize-autoloader

    # Configurar env de Laravel
    - name: Configure env
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_DESTINATION: ${{ secrets.FTP_DESTINATION }}
      run: |
        php artisan config:cache

    # Subir al servidor GoogieHost via FTP
    - name: Upload files to GoogieHost via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_DESTINATION }}

    - name: Set permissions for storage and bootstrap/cache directories
      run: |
        curl -sS https://getcomposer.org/installer | php
        php artisan storage:link
        chmod -R 775 /public_html/storage
        chmod -R 775 /bootstrap/cache

    # Ejecutar comandos de Laravel post-deployment
    - name: Run Laravel commands post-deployment
      run: |
        curl -sS https://getcomposer.org/installer | php
        php artisan key:generate
        php artisan migrate --force